services:
    db:
        image: postgres:16
        environment:
            POSTGRES_DB: task_control
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: secret
            TZ: Asia/Almaty
        volumes:
            - pgdata:/var/lib/postgresql/data
        # Раскомментируй, если хочешь подключаться к БД с хоста (DBeaver, pgAdmin и т.п.)
        ports:
            - "55432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U symfony -d app"]
            interval: 5s
            timeout: 3s
            retries: 10

    app:
        build: .
        depends_on:
            db:
                condition: service_healthy
        environment:
            APP_ENV: dev
            TZ: Asia/Almaty
        volumes:
            - ./:/var/www/html:delegated

    web:
        image: nginx:1.27-alpine
        depends_on:
            - app
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        environment:
            TZ: Asia/Almaty

volumes:
    pgdata:
